name: Deploy Docker Container on EC2

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate EC2 connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 60s
          script: |
            echo "Connessione EC2 stabilita con successo"
            whoami
            pwd
            docker --version || echo "Docker non installato"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 600s
          command_timeout: 30m
          script: |
            set -e
            
            # verifica che la repo esista altrimenti la clona
            if [ ! -d "/home/ec2-user/Music-Databese-Query-App-for-Distributed-Systems-on-Cloud" ]; then
              echo "Clonando il repository..."
              cd /home/ec2-user
              git clone https://github.com/YOUR_USERNAME/Music-Databese-Query-App-for-Distributed-Systems-on-Cloud.git
            fi
            
            # entra nella directory del progetto
            cd /home/ec2-user/Music-Databese-Query-App-for-Distributed-Systems-on-Cloud
            
            # effettuo una fetch e reset per assicurarmi di avere l'ultima versione
            echo "Effettuando pull del repository..."
            git fetch origin
            git reset --hard origin/main
            
            # fermo e rimuovo tutti i container che usano la porta 8080
            echo "Cleanup: Fermando tutti i container che usano la porta 8080..."
            docker ps -q --filter "publish=8080" | xargs -r docker stop || true
            docker ps -aq --filter "publish=8080" | xargs -r docker rm || true
            
            # aspetto per assicurarmi che le risorse siano liberate
            echo "Attendendo la liberazione delle risorse..."
            sleep 5
            
            # verifico che la porta 8080 sia libera
            echo "Verificando che la porta 8080 sia libera..."
            if netstat -tulpn 2>/dev/null | grep :8080 || ss -tulpn 2>/dev/null | grep :8080; then
              echo "Attenzione: la porta 8080 è ancora in uso"
              # Forza la terminazione di processi sulla porta 8080
              sudo fuser -k 8080/tcp 2>/dev/null || true
              sleep 3
            else
              echo "Porta 8080 è libera"
            fi
            
            # pulisco le immagini Docker non utilizzate
            echo "Pulizia immagini Docker..."
            docker system prune -f
            
            # build del container Docker
            echo "Ricostruendo il container Docker..."
            if ! docker build -f Dockerfile.dockerfile -t musicapp-server .; then
              echo "Errore durante la build del container Docker"
              exit 1
            fi
            
            # avvio il container Docker
            if ! docker run -d \
              --name musicapp-server \
              -p 8080:8080 \
              --restart unless-stopped \
              musicapp-server; then
              echo "Errore nell'avvio del container"
              echo "Verifica dei container in esecuzione:"
              docker ps -a
              echo "Verifica dell'uso della porta 8080:"
              netstat -tulpn 2>/dev/null | grep :8080 || ss -tulpn 2>/dev/null | grep :8080 || echo "Nessun processo sulla porta 8080"
              exit 1
            fi
            
            # aspetto che il container si avvii
            echo "Verifica del container in esecuzione..."
            sleep 15
            
            # controllo lo stato del container
            if docker ps | grep -q "musicapp-server"; then
              echo "Container musicapp-server è in esecuzione"
              docker ps -a --filter "name=musicapp-server"
            else
              echo "Container musicapp-server NON è in esecuzione"
              echo "Log del container:"
              docker logs musicapp-server 2>/dev/null || echo "Nessun log disponibile"
              exit 1
            fi
            
            # controllo che lapplicazione risponda correttamente
            echo "Test di connettività all'applicazione..."
            for i in {1..10}; do
                # Verifica che la porta sia aperta e in ascolto (senza inviare dati HTTP)
              if timeout 3 bash -c "</dev/tcp/localhost/8080" 2>/dev/null; then
                echo "Applicazione risponde correttamente sulla porta 8080"
                break
              else
                echo "Tentativo $i/10 - Applicazione non ancora pronta, attendo 10 secondi..."
                sleep 10
              fi
              if [ $i -eq 10 ]; then
                echo "Applicazione non risponde dopo 10 tentativi"
                echo "Log del container:"
                docker logs musicapp-server
                echo "Stato del container:"
                docker ps -a --filter "name=musicapp-server"
                exit 1
              fi
            done

            # invio una notifica SNS per segnalare il completamento del deploy tramite git action
            sudo -u ec2-user aws sns publish --region us-east-1 --topic-arn $(sudo -u ec2-user aws sns list-topics --region us-east-1 --query "Topics[?contains(TopicArn, 'musicapp-server-setup-complete')].TopicArn" --output text) --subject "MusicApp Server Setup" --message "Il setup del server EC2 MusicApp è stato completato con successo dopo la git action."
            
            echo "Deploy completato!"
